#!/bin/bash
usage()
{
	echo 'Usage: git mkrepo REPOSITORYNAME [-p <private?>] [-d "DESCRIPTION"] [-u http://HOMEPAGE] [-r SSH<default>|HTTP]'
}

if [[ ! -z "$1" || ! "$1" -eq "-"  ]];
then
	REPO=$1
	DATA="\"name\":\"$REPO\""
	# Ignore first argument
	OPTIND=2
	REMOTE=SSH
	while getopts ":pd:u:" OPT; do
	  echo $OPTIND
	  echo $OPT
	  case $OPT in
	    p) DATA="$DATA,\"private\":true"; echo $DATA;;
	    d) DATA="$DATA,\"description\":\"$OPTARG\"";;
	    u) DATA="$DATA,\"homepage\":\"$HOMEPAGE\"";;
	    r) REMOTE=$OPTARG;;
	    \?)
	      usage
	      exit 1
	      ;;
	  esac
	done

	DATA="{$DATA}"
	echo "POST: $DATA"
	curl --netrc --data "$DATA" "https://api.github.com/user/repos" 

	[[ "$REMOTE" -eq "HTTP" ]] && REMOTEURL="https://github.com/$USERNAME/$REPO"
	[[ "$REMOTE" -eq "SSH" ]] && REMOTEURL="git@github.com:$USERNAME/$REPO.git"

	mkdir $REPO
	cd $REPO && git init && git remote add origin $REMOTEURL

else
	usage
fi		