#!/bin/bash
read -p "github username: " USERNAME
echo "github password: " 
read -s PASSWORD
read -p "repository name: " REPO
read -p "description: "	DESC
read -p "homepage: " HOMEPAGE
read -p "private [n]: " PRIVATE
read -p "add README.md [y]:" README

DATA=''
[[ ! -z "$REPO" ]] && DATA='"name":"'$REPO'",'
[[ ! -z "$DESC" ]] && DATA=$DATA'"description":"'$DESC'",'
[[ ! -z "$HOMEPAGE" ]] && DATA=$DATA'"homepage":"'$HOMEPAGE'",'
[[ "$PRIVATE" =~ [yY] ]] && DATA=$DATA'"private":true,'
[[ -z "$README" || "$README" =~ [yY] ]] && DATA=$DATA'"auto_init":true'
DATA='{'$DATA'}'

curl -u $USERNAME:$PASSWORD https://api.github.com/user/repos --data $DATA

git init
git remote add origin git@github.com:$USERNAME/$REPO.git
git pull origin master
