#!/bin/bash
echo $#
if [ $# -gt 1 ]; then
	USERNAME=$1
	REPO=$2
	curl -u $USERNAME https://api.github.com/user/repos -d '{"name":"'"$REPO"'"}'
	# Remember replace USER with your username and REPO with your repository/application name!
	git init
	git remote add origin http://www.github.com/$USERNAME/$REPO
	git push origin master
else
    echo "Usage: $ createGITRepoFromCLI username RepositoryName"
fi
