#!/bin/bash
read -p "github username: " USERNAME
echo "github password: " 
read -s PASSWORD
read -p "repository name: " REPO
read -p "description: "	DESC
read -p "homepage: " HOMEPAGE
read -p "private [yY]: " PRIVATE
read -p "add README.md [yY]:" README

DATA='"name":"'$REPO'","description":"'$DESC'","homepage":"'$HOMEPAGE'"'

if [[ "$PRIVATE" =~ [yY] ]]; then DATA=$DATA'","private": true'; fi
if [[ "$README" =~ [yY] ]]; then DATA=$DATA'","auto_init": true'; fi

curl -u $USERNAME:$PASSWORD https://api.github.com/user/repos -d '{'$DATA'}'

git init
git remote add origin http://www.github.com/$USERNAME/$REPO
git pull origin master
